version: '3.3'
services:
  percona-local:
    container_name: percona-local
    image: percona:latest
    environment:
      MYSQL_DATABASE: go-hexagonal-service
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    restart: always
    networks:
      - local-net

networks:
  local-net: {}
